### ISSUE TITLE
Presentation by Fred, AITI on Open Source at the Centers

### ISSUE THREAD

**Issue by enockseth** [LinuxAccra-UserGroup/SFD2020#18]

**Comment by papaspiro** [comment]
He does not seem to keen . Do we use another person?

**Comment by enockseth** [comment]
Anyone else from AITI ready to, else no problem. Kindly ping Nana again let's see

**Comment by enockseth** [comment]
@papaspiro any progress on this?

**Comment by enockseth** [comment]
No longer possible
