### ISSUE TITLE
Presentation on Open Hardware by Sandy

### ISSUE THREAD

**Issue by brightmorkli37** [LinuxAccra-UserGroup/SFD2020#5]
Sandy Fafali will give a recorded presentation on "Open Hardware"

- [ ] Recorded video should be ready by Wednesday 16th September, 2020

- [ ] Video should a of maximum 5 minutes

**Comment by enockseth** [comment]
Promised to deliver by close of day today 7pm but not received yet

**Comment by enockseth** [comment]
Failed, no response and not broadcasted
