### ISSUE TITLE
Program Outline

### ISSUE THREAD

**Issue by brightmorkli37** [LinuxAccra-UserGroup/SFD2020#6]
Outline of the Program
Number of presentations to be made in order

**Comment by enockseth** [comment]
1. Welcome Address - Sabra
1. Keynote - Nii Okai
1. FOSS Overview / Use Cases - Enock
1. ~~Nyansapo OS - Rexford~~
1. ~~Open Hardware - Fafali~~
1. OpenStreetMap - Angela, OSM Ghana
1. ~~Automation using Bots - Bright~~
1. Closing Remarks - Sabra
